services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - "${HOME}/opt/state/uptime-kuma/data:/app/data"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ingress

networks:
  ingress:
    external: true
    name: ingress
